language: python
matrix:
  include:
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.5-dev
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: 3.9
      dist: xenial
      sudo: true
install:
  - python setup.py -q install
script:
  - python tests.py
